flent/runners.py

Occassionally was matching IPV6 addresses subparts.
Signed-off-by: Matthias Tafelmeier <matthias.tafelmeier@gmx.net>

ss_runner: fix ipv4 addr regex

---

flent/gui.py

Commit 46a2154 introduce the bug that completly remove import
matplotlib, and fixed at commit 2d0cd05a. But still have bug when
opening a new data file, it will hang by this:
```
Exception in thread Thread-3:
Traceback (most recent call last):
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python3.6/multiprocessing/pool.py", line 463, in _handle_results
task = get()
File "/usr/lib/python3.6/multiprocessing/connection.py", line 251, in recv
return _ForkingPickler.loads(buf.getbuffer())
File "/usr/lib/python3.6/site-packages/matplotlib/figure.py", line 1688, in __setstate__
mgr = plt._backend_mod.new_figure_manager_given_figure(num, self)
File …
```

gui: Fix matplotlib causing runtime error when open file

---

flent/batch.py
flent/settings.py

Re-arranged gen_filename a bit now that some parts of the filename are optional.
Signed-off-by: Pete Heist <pete@heistp.net>

batch: Add --batch-no-timestamp command line argument

---

flent/runners.py
flent/settings.py

This is only a start on what we discussed, as it's over my head at the moment how to make this setting per-flow and have it affect the UDP packet size. Sorry if short on time at the moment to dig into it further. :)
Signed-off-by: Pete Heist <pete@heistp.net>

runners: Add --send-size flag for netperf send size (-m/-M)

---

README.rst
doc/quickstart.rst

The goal of this PR is to provide macOS users with the necessary steps to install and run Flent successfully.
Some additional things I added:
- cleaned up the documentation a bit to use some code blocks for better readability
- added the three public netperf test servers users can use if they don't run netperf on a machine of their own
This PR was created to address this issue I created:
https://github.com/tohojo/flent/issues/207

Install instructions for macOS

---

flent/runners.py
flent/util.py

irtt currently only accepts IPv6 addresses surrounded by brackets.
If the host contains an IPv6 address literal (as identified by
ipaddress.IPv6Address), surround the host with brackets before
passing to irtt.
This should address #238.

runners: Bracket IPv6 addresses before passing to irtt

---

flent/util.py

Changed the equations (7-27) and (7-29) by considering
the default value of sT as 1 and Bpl as 4.3 as outlined
in the G.107 recommendation. Updated the link for the
reference implementation to the latest one.
Fixes #247.
Signed-off-by: Hrishikesh Athalye <hathalye7@hotmail.com>

util: Default value of sT and Bpl for MOS score calculation

---

flent/runners.py

When we run netserver along with ss on the same node, ss data parsing breaks. Skip ss stats of netserver user.

runners: fix ss data parsing when run along with netserver

---

flent/runners.py
flent/settings.py
flent/util.py

This adds a persistent lookup cache for runner probing results. The primary use case is running many tests on remote hosts, where the per-run probing can add significant test time overhead.

Persistent runner lookup cache

---

flent/__init__.py
flent/aggregators.py
flent/batch.py
flent/loggers.py
flent/runners.py
flent/util.py
unittests/test_parsers.py

This pull request contains a number of fixes that significantly improves the scaling of Flent when spawning a lot of runners:
- Fix the SsRunner to only parse output once when running multiple duplicate runners (i.e., for multiple flows on the same host).
- Move parsing of runner output into separate subprocesses to let it run in parallel without the Python GIL
- Fix a bunch of inefficiencies in the way Flent forks off runner child processes and the Python threads that monitor them
- Fix the behaviour when a test is interrupted so runners are more reliably shut down in a timely manner
- Improve memory usage by only reading the tool output into memory when it is absolutely needed, and keeping it there for as short a time as possible
- in particular, turn all parsers into stream-based …

Runner scalability

---

flent/gui.py
packaging/rpm/flent.spec

Update the RPM .spec to fix the recommended dependencies on Fedora for running
the GUI. Also add the GUI import error message to aid debugging.
Fixes #259.

Fix dependencies on Fedora

---

flent/gui.py

The Qt ProgressBar::setValue() method expects integers and passing floats
causes a crash. Round the calculation to make sure this doesn't happen.
Fixes #261.

gui: Don't pass floats to progressbar.setValue()

---

flent/runners.py

The change to multi-step parsing broke the parsing in DelegatingRunner
derivatives since their children's parser method never got called. Provide
a default implementation for do_parse() in the BaseRunner class that just
chains to child runners.
Fixes #263.
Signed-off-by: Toke Høiland-Jørgensen <toke@toke.dk>

runners: Provide default implementation for do_parse()

---

flent/aggregators.py
flent/runners.py

Since there seems to be issues with the multiprocessing module on OSX, and attempts to find a workaround has failed, let's just disable the parallel parsing entirely on OSX.
Fixes #268

Disable multiprocess parsing on OSX

---

flent/gui.py

@mahsan76 reports:
> There is an issue in Flent 2.0.1 , after loading multiple test files ( e.g 5 or 6 ) and adding combining them,
> when i click close all tab , it works ok and all tabs are closed...
> but then when i want to open 5 or 6 files again , the process gets stuck with the following exception in ubuntu bash terminal:
> 
> #########################################################################################
> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.9/threading.py", line 892, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/lib/python3.9/multiprocessing/pool.py", line 592, in _handle_results
> …

gui: Don't try to redraw received plot if widget was removed

---

flent/plotters.py

The handling of the internal renderer objects changed in Matplotlib 3.6, and we
haven't adjusted to the new API. Move the existing logic into a helper function
so we can use it consistently, and try calling the new matplotlib API before
falling back to the old logic.
Fixes #291.

plotters: Adjust to new renderer handling in Matplotlib 3.6

---

.github/workflows/selftests.yml
flent/plotters.py
setup.cfg
unittests/test_helpers.py

The distutils module was deprecated in Python 3.12, so let's stop using it.
Fixes #296.

Fix running on Python 3.12

---

flent/plotters.py

The matplotlib package removed all axis directions from the base parameters for logarithmic scaling functions in v3.3.0 and up.
This commit supports both the original "basex" and "basey" parameters for older versions of matplotlib and the new "base" parameter for more recent versions of matplotlib.

Fixed log-scale matplotlib compatibility for v3.3

---

flent/metadata.py
flent/runners.py

Use raw strings literals for the affected regexes
(venv-flent) $ flent -V
/path/to/flent/flent/metadata.py:247: SyntaxWarning: invalid escape sequence '\d'
m = re.search("(qlen|txqueuelen) (\d+)", output)
/path/to/flent/flent/metadata.py:259: SyntaxWarning: invalid escape sequence '\w'
m = re.search("Duplex: (\w+)", output)
Starting Flent 2.1.1+git.6c8dce50 using Python 3.12.4. Flent v2.1.1+git.6c8dce50.
Running on Python 3.12.4 (main, Jun  9 2024, 22:05:49) [GCC 13.2.0]. No matplotlib found. Plots won't be available.
No usable Qt version found. GUI won't work.
ERROR: Missing test name.

Fix SyntaxWarning for '\w' '\d' in regexes

---

setup.py

The last python version deprecation change forgot `setup.py`.
Update that to be on the same level as in `flent/__init__.py`
Fixes: abe88692ca94f5dde96f3ea0889ef2c5035c2a27
Last changed in : 43c82cd01556ef746db608e84eba9a3b5a141aa0

Remove forgotten support for python 3.5

---

README.rst
doc/_templates/index.html
doc/misc.rst
doc/quickstart.rst

Bunch of minor fixes and then adding nix to the list of oses that packages flent.
The fixes are mostly cosmetic tweaks, more info in the commit messages.

Doc tweaks
